var hierarchy =
[
    [ "AbstractController< InputType, OutputType >", "d0/d5c/classAbstractController.html", [
      [ "PID< VelocityType, OutputType >", "d8/da9/classPID.html", null ],
      [ "PID< PositionType, VelocityType >", "d8/da9/classPID.html", null ],
      [ "PID< InputType, OutputType >", "d8/da9/classPID.html", null ]
    ] ],
    [ "AbstractController< PositionType, VelocityType >", "d0/d5c/classAbstractController.html", null ],
    [ "AbstractController< VelocityType, OutputType >", "d0/d5c/classAbstractController.html", null ],
    [ "AMTEncoderBase", "db/d69/classAMTEncoderBase.html", [
      [ "AMTEncoderExti", "df/d9b/classAMTEncoderExti.html", null ]
    ] ],
    [ "IM920sL::BaseIM920sL", "d7/dd8/classIM920sL_1_1BaseIM920sL.html", null ],
    [ "BitRange", "d6/d01/structBitRange.html", null ],
    [ "PS5::Button", "d6/de5/structPS5_1_1Button.html", null ],
    [ "CanSystem::CANConfig", "d7/d93/structCanSystem_1_1CANConfig.html", null ],
    [ "CanSystem::CanErrorTracker", "d9/d7c/classCanSystem_1_1CanErrorTracker.html", null ],
    [ "CanSystem::CanManager::CANFifoConfig", "dd/d34/structCanSystem_1_1CanManager_1_1CANFifoConfig.html", null ],
    [ "CanSystem::CANMessage", "d2/d4a/structCanSystem_1_1CANMessage.html", null ],
    [ "CanSystem::CANStatus", "d7/db6/structCanSystem_1_1CANStatus.html", null ],
    [ "CommandReceiver< MAX_SIZE >", "d0/d45/classCommandReceiver.html", null ],
    [ "DJI::CriticalSection", "db/d04/classDJI_1_1CriticalSection.html", null ],
    [ "proto_can::Device< DeviceTYPE >", "d2/deb/classproto__can_1_1Device.html", null ],
    [ "proto_can::Device< PC::DeviceType::SOLENOID >", "d2/deb/classproto__can_1_1Device.html", null ],
    [ "proto_can::DeviceID< TYPE >", "dd/d82/classproto__can_1_1DeviceID.html", null ],
    [ "proto_can::DeviceID< DeviceTYPE >", "dd/d82/classproto__can_1_1DeviceID.html", null ],
    [ "proto_can::DeviceID< PC::DeviceType::SOLENOID >", "dd/d82/classproto__can_1_1DeviceID.html", null ],
    [ "proto_can::DeviceSchema< TYPE >", "d9/de8/structproto__can_1_1DeviceSchema.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::MOCK_MOTOR >", "d2/de2/structproto__can_1_1DeviceSchema_3_01DeviceType_1_1MOCK__MOTOR_01_4.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::MOTOR >", "d5/d25/structproto__can_1_1DeviceSchema_3_01DeviceType_1_1MOTOR_01_4.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::SENSOR >", "dd/d4e/structproto__can_1_1DeviceSchema_3_01DeviceType_1_1SENSOR_01_4.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::SOLENOID >", "d0/d8c/structproto__can_1_1DeviceSchema_3_01DeviceType_1_1SOLENOID_01_4.html", null ],
    [ "PS5::DualSense", "d7/db3/classPS5_1_1DualSense.html", null ],
    [ "CanSystem::ErrorCounters", "df/d6b/structCanSystem_1_1ErrorCounters.html", null ],
    [ "DJI::ESC", "d4/d2e/classDJI_1_1ESC.html", null ],
    [ "DJI::ESCData", "d2/df4/structDJI_1_1ESCData.html", null ],
    [ "FormatStr", "de/d83/structFormatStr.html", null ],
    [ "proto_can::FrameLayer", "d6/d2e/classproto__can_1_1FrameLayer.html", null ],
    [ "GPIO_Mgr< PIN_COUNT >", "d6/d4e/classGPIO__Mgr.html", null ],
    [ "GPIO_Mgr< 3 >", "d6/d4e/classGPIO__Mgr.html", null ],
    [ "GPIO_Mgr< 4 >", "d6/d4e/classGPIO__Mgr.html", null ],
    [ "GPIO_Mgr< 6 >", "d6/d4e/classGPIO__Mgr.html", null ],
    [ "GPIOConfig", "d4/dff/structGPIOConfig.html", null ],
    [ "CanSystem::ICanController", "d6/dca/classCanSystem_1_1ICanController.html", [
      [ "CanSystem::MockCanProfile", "d9/d76/classCanSystem_1_1MockCanProfile.html", null ]
    ] ],
    [ "ICanManager", null, [
      [ "CanSystem::CanManager", "d1/d4a/classCanSystem_1_1CanManager.html", null ]
    ] ],
    [ "CanSystem::IdStats", "de/df2/structCanSystem_1_1IdStats.html", null ],
    [ "LogLite", "d9/d24/classLogLite.html", null ],
    [ "Motoron::Master", "da/d4c/classMotoron_1_1Master.html", null ],
    [ "proto_can::Master", "d3/da4/classproto__can_1_1Master.html", null ],
    [ "proto_can::MessageID", "d9/d34/classproto__can_1_1MessageID.html", null ],
    [ "proto_can::Messenger", "d8/dd9/classproto__can_1_1Messenger.html", null ],
    [ "Motion< VelocityType, PositionType, OutputType >", "d1/d3c/classMotion.html", null ],
    [ "MotionController< VelocityType, PositionType, OutputType >", "d9/d58/classMotionController.html", null ],
    [ "MotionMode< OutputType >", "df/d66/classMotionMode.html", null ],
    [ "MotionMode< PositionType >", "df/d66/classMotionMode.html", null ],
    [ "MotionMode< VelocityType >", "df/d66/classMotionMode.html", null ],
    [ "proto_can::NoSchema", "de/d88/structproto__can_1_1NoSchema.html", null ],
    [ "IM920sL::Packet", "db/d29/structIM920sL_1_1Packet.html", null ],
    [ "stdr::PID", "dc/d22/classstdr_1_1PID.html", null ],
    [ "PIDConfig", "dc/df1/structPIDConfig.html", null ],
    [ "PIDGain", "d4/d2c/structPIDGain.html", null ],
    [ "PIDProfile", "d8/daf/structPIDProfile.html", null ],
    [ "proto_can::ProtocolHeader", "df/db1/classproto__can_1_1ProtocolHeader.html", null ],
    [ "proto_can::RawMessage", "df/d58/structproto__can_1_1RawMessage.html", null ],
    [ "CanSystem::SoftwareErrorFlags", "d0/d5e/structCanSystem_1_1SoftwareErrorFlags.html", null ],
    [ "solenoid_ctrl::SolenoidDevice< SOL_COUNT, DIP_COUNT >", "dd/d8e/classsolenoid__ctrl_1_1SolenoidDevice.html", null ],
    [ "solenoid_ctrl::SolenoidMaster< SOL_COUNT >", "dd/d48/classsolenoid__ctrl_1_1SolenoidMaster.html", null ],
    [ "TelemSender< MAX_SIZE >", "d0/dc3/classTelemSender.html", null ],
    [ "TimerMgr", "d5/db3/classTimerMgr.html", null ],
    [ "CanSystem::TimingConfig", "de/da9/structCanSystem_1_1TimingConfig.html", null ],
    [ "CanSystem::MockCanProfile::TxRecord", "d0/d87/structCanSystem_1_1MockCanProfile_1_1TxRecord.html", null ],
    [ "UartManager", "dd/d1a/classUartManager.html", null ]
];