var hierarchy =
[
    [ "IM920sL::BaseIM920sL", "classIM920sL_1_1BaseIM920sL.html", null ],
    [ "BitRange", "structBitRange.html", null ],
    [ "PS5::Button", "structPS5_1_1Button.html", null ],
    [ "CanSystem::CANConfig", "structCanSystem_1_1CANConfig.html", null ],
    [ "CanSystem::CanErrorTracker", "classCanSystem_1_1CanErrorTracker.html", null ],
    [ "CanSystem::CANMessage", "structCanSystem_1_1CANMessage.html", null ],
    [ "CanSystem::CANStatus", "structCanSystem_1_1CANStatus.html", null ],
    [ "proto_can::Device< DeviceTYPE >", "classproto__can_1_1Device.html", null ],
    [ "proto_can::Device< PC::DeviceType::MOCK_MOTOR >", "classproto__can_1_1Device.html", null ],
    [ "proto_can::DeviceID< TYPE >", "classproto__can_1_1DeviceID.html", null ],
    [ "proto_can::DeviceID< DeviceTYPE >", "classproto__can_1_1DeviceID.html", null ],
    [ "proto_can::DeviceSchema< TYPE >", "structproto__can_1_1DeviceSchema.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::MOCK_MOTOR >", "structproto__can_1_1DeviceSchema_3_01DeviceType_1_1MOCK__MOTOR_01_4.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::MOTOR >", "structproto__can_1_1DeviceSchema_3_01DeviceType_1_1MOTOR_01_4.html", null ],
    [ "proto_can::DeviceSchema< DeviceType::SENSOR >", "structproto__can_1_1DeviceSchema_3_01DeviceType_1_1SENSOR_01_4.html", null ],
    [ "PS5::DualSense", "classPS5_1_1DualSense.html", null ],
    [ "CanSystem::ErrorCounters", "structCanSystem_1_1ErrorCounters.html", null ],
    [ "DJI::ESC", "classDJI_1_1ESC.html", null ],
    [ "DJI::ESCData", "structDJI_1_1ESCData.html", null ],
    [ "proto_can::FrameLayer", "classproto__can_1_1FrameLayer.html", null ],
    [ "CanSystem::ICanController", "classCanSystem_1_1ICanController.html", [
      [ "CanSystem::MockCanProfile", "classCanSystem_1_1MockCanProfile.html", null ]
    ] ],
    [ "CanSystem::IdStats", "structCanSystem_1_1IdStats.html", null ],
    [ "Motoron::Master", "classMotoron_1_1Master.html", null ],
    [ "proto_can::Master", "classproto__can_1_1Master.html", null ],
    [ "proto_can::MessageID", "classproto__can_1_1MessageID.html", null ],
    [ "EmbeddedProto::MessageInterface", null, [
      [ "robot::Telemetry< V_SIZE, MSG_SIZE >", "classrobot_1_1Telemetry.html", null ],
      [ "common::PIDConfig", "classcommon_1_1PIDConfig.html", null ],
      [ "devices::DeviceStatus", "classdevices_1_1DeviceStatus.html", null ],
      [ "devices::RequestStatus", "classdevices_1_1RequestStatus.html", null ],
      [ "devices::ResetCommand", "classdevices_1_1ResetCommand.html", null ],
      [ "devices::mock_motor::Command", "classdevices_1_1mock__motor_1_1Command.html", null ],
      [ "devices::mock_motor::Data", "classdevices_1_1mock__motor_1_1Data.html", null ],
      [ "devices::motor::Command", "classdevices_1_1motor_1_1Command.html", null ],
      [ "devices::motor::Data", "classdevices_1_1motor_1_1Data.html", null ],
      [ "devices::robomas::Command< Command_motors_REP_LENGTH >", "classdevices_1_1robomas_1_1Command.html", null ],
      [ "devices::robomas::Data< Data_motors_REP_LENGTH >", "classdevices_1_1robomas_1_1Data.html", null ],
      [ "devices::robomas::MotorCommand", "classdevices_1_1robomas_1_1MotorCommand.html", null ],
      [ "devices::robomas::PIDConfig", "classdevices_1_1robomas_1_1PIDConfig.html", null ],
      [ "devices::robomas::RobomasData", "classdevices_1_1robomas_1_1RobomasData.html", null ],
      [ "devices::robomas::TrajectoryProfile", "classdevices_1_1robomas_1_1TrajectoryProfile.html", null ],
      [ "robot::Controller", "classrobot_1_1Controller.html", null ],
      [ "robot::DJI", "classrobot_1_1DJI.html", null ],
      [ "robot::Locomotion", "classrobot_1_1Locomotion.html", null ],
      [ "robot::RobotCommand< RobotCommand_version_LENGTH >", "classrobot_1_1RobotCommand.html", null ],
      [ "robot::SystemCommand", "classrobot_1_1SystemCommand.html", null ],
      [ "robot::Telemetry< Telemetry_version_LENGTH, Telemetry_log_LENGTH >", "classrobot_1_1Telemetry.html", null ],
      [ "robot::xyz_f", "classrobot_1_1xyz__f.html", null ],
      [ "robot::xyz_i", "classrobot_1_1xyz__i.html", null ]
    ] ],
    [ "proto_can::Messenger", "classproto__can_1_1Messenger.html", null ],
    [ "MockMotor", "classMockMotor.html", null ],
    [ "proto_can::NoSchema", "structproto__can_1_1NoSchema.html", null ],
    [ "stdr::PID", "classstdr_1_1PID.html", null ],
    [ "proto_can::ProtocolHeader", "classproto__can_1_1ProtocolHeader.html", null ],
    [ "proto_can::RawMessage", "structproto__can_1_1RawMessage.html", null ],
    [ "CanSystem::SoftwareErrorFlags", "structCanSystem_1_1SoftwareErrorFlags.html", null ],
    [ "TelemController< MAX_SIZE >", "classTelemController.html", null ],
    [ "CanSystem::TimingConfig", "structCanSystem_1_1TimingConfig.html", null ],
    [ "CanSystem::MockCanProfile::TxRecord", "structCanSystem_1_1MockCanProfile_1_1TxRecord.html", null ]
];